### PR TITLE
toggle show orphaned files

### PR DESCRIPTION
**Pull request by Iurie**
toggle show/hide orphaned files

### CODE REVIEW

**Comment by fourier** [comment]
First in order to take in the nontrivial changes, I had to ask if you've signed the copyright papers to FSF?
Read here: https://github.com/fourier/ztree#copyright-issues for details.

**Comment by Iurie** [comment]
I've sent today the signed agreement to "FSF". I'm waiting for countersigned document (maybe I'll receive it next week).

**Comment by fourier** [comment]
Thanks let me know when you've received the papers back.

**Comment by Iurie** [comment]
Hi Alexey,
I've received the countersigned document.

**Comment by fourier** [comment]
Great! Could you please drop me a mail with your name/second nam?

**Comment by fourier** [comment]
Thanks, submitted!

**Pull request merged**
